[2025-03-24T17:25:12.027+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T17:25:12.033+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_pipeline.dbt_dq_check manual__2025-03-24T16:17:51.573790+00:00 [queued]>
[2025-03-24T17:25:12.036+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_pipeline.dbt_dq_check manual__2025-03-24T16:17:51.573790+00:00 [queued]>
[2025-03-24T17:25:12.036+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T17:25:12.039+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_dq_check> on 2025-03-24 16:17:51.573790+00:00
[2025-03-24T17:25:12.043+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1061) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T17:25:12.042+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_pipeline', 'dbt_dq_check', 'manual__2025-03-24T16:17:51.573790+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp9g2g8hig']
[2025-03-24T17:25:12.043+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask dbt_dq_check
[2025-03-24T17:25:12.043+0000] {standard_task_runner.py:72} INFO - Started process 1062 to run task
[2025-03-24T17:25:12.060+0000] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_pipeline.dbt_dq_check manual__2025-03-24T16:17:51.573790+00:00 [running]> on host 5534f92a2ac4
[2025-03-24T17:25:12.088+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_dq_check' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T16:17:51.573790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T16:17:51.573790+00:00'
[2025-03-24T17:25:12.089+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T17:25:12.093+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T17:25:12.093+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec data_pipeline-dbt-1 dbt test --fail-fast']
[2025-03-24T17:25:12.097+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T17:25:12.999+0000] {subprocess.py:106} INFO - [0m17:25:12  Running with dbt=1.9.0
[2025-03-24T17:25:13.154+0000] {subprocess.py:106} INFO - [0m17:25:13  Registered adapter: postgres=1.9.0
[2025-03-24T17:25:13.400+0000] {subprocess.py:106} INFO - [0m17:25:13  Found 3 models, 3 data tests, 1 source, 430 macros
[2025-03-24T17:25:13.402+0000] {subprocess.py:106} INFO - [0m17:25:13
[2025-03-24T17:25:13.403+0000] {subprocess.py:106} INFO - [0m17:25:13  Concurrency: 1 threads (target='dev')
[2025-03-24T17:25:13.403+0000] {subprocess.py:106} INFO - [0m17:25:13
[2025-03-24T17:25:13.501+0000] {subprocess.py:106} INFO - [0m17:25:13  1 of 3 START test source_not_null_public_premier_league_2425_raw_away_team ..... [RUN]
[2025-03-24T17:25:13.533+0000] {subprocess.py:106} INFO - [0m17:25:13  1 of 3 PASS source_not_null_public_premier_league_2425_raw_away_team ........... [[32mPASS[0m in 0.03s]
[2025-03-24T17:25:13.534+0000] {subprocess.py:106} INFO - [0m17:25:13  2 of 3 START test source_not_null_public_premier_league_2425_raw_home_team ..... [RUN]
[2025-03-24T17:25:13.547+0000] {subprocess.py:106} INFO - [0m17:25:13  2 of 3 PASS source_not_null_public_premier_league_2425_raw_home_team ........... [[32mPASS[0m in 0.01s]
[2025-03-24T17:25:13.548+0000] {subprocess.py:106} INFO - [0m17:25:13  3 of 3 START test source_not_null_public_premier_league_2425_raw_matchday ...... [RUN]
[2025-03-24T17:25:13.562+0000] {subprocess.py:106} INFO - [0m17:25:13  3 of 3 PASS source_not_null_public_premier_league_2425_raw_matchday ............ [[32mPASS[0m in 0.01s]
[2025-03-24T17:25:13.571+0000] {subprocess.py:106} INFO - [0m17:25:13
[2025-03-24T17:25:13.572+0000] {subprocess.py:106} INFO - [0m17:25:13  Finished running 3 data tests in 0 hours 0 minutes and 0.17 seconds (0.17s).
[2025-03-24T17:25:13.595+0000] {subprocess.py:106} INFO - [0m17:25:13
[2025-03-24T17:25:13.596+0000] {subprocess.py:106} INFO - [0m17:25:13  [32mCompleted successfully[0m
[2025-03-24T17:25:13.596+0000] {subprocess.py:106} INFO - [0m17:25:13
[2025-03-24T17:25:13.597+0000] {subprocess.py:106} INFO - [0m17:25:13  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-03-24T17:25:14.769+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T17:25:14.778+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T17:25:14.779+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=e2e_data_pipeline, task_id=dbt_dq_check, run_id=manual__2025-03-24T16:17:51.573790+00:00, execution_date=20250324T161751, start_date=20250324T172512, end_date=20250324T172514
[2025-03-24T17:25:14.823+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T17:25:14.831+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T17:25:14.832+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
