[2025-03-24T15:59:42.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T15:59:42.320+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_pipeline.create_table manual__2025-03-24T15:59:38.939254+00:00 [queued]>
[2025-03-24T15:59:42.323+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_pipeline.create_table manual__2025-03-24T15:59:38.939254+00:00 [queued]>
[2025-03-24T15:59:42.323+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T15:59:42.326+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_table> on 2025-03-24 15:59:38.939254+00:00
[2025-03-24T15:59:42.330+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T15:59:42.329+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_pipeline', 'create_table', 'manual__2025-03-24T15:59:38.939254+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpxkusyw39']
[2025-03-24T15:59:42.330+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask create_table
[2025-03-24T15:59:42.330+0000] {standard_task_runner.py:72} INFO - Started process 221 to run task
[2025-03-24T15:59:42.347+0000] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_pipeline.create_table manual__2025-03-24T15:59:38.939254+00:00 [running]> on host 34d5be02b70d
[2025-03-24T15:59:42.370+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_pipeline' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T15:59:38.939254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T15:59:38.939254+00:00'
[2025-03-24T15:59:42.370+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T15:59:42.379+0000] {logging_mixin.py:190} INFO - Table created successfully!
[2025-03-24T15:59:42.379+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-24T15:59:42.382+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T15:59:42.382+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=e2e_data_pipeline, task_id=create_table, run_id=manual__2025-03-24T15:59:38.939254+00:00, execution_date=20250324T155938, start_date=20250324T155942, end_date=20250324T155942
[2025-03-24T15:59:42.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T15:59:42.440+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T15:59:42.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
